// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PokeGame.Infrastructure;

#nullable disable

namespace PokeGame.PostgreSQL.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20260630143800_CreateSpeciesTable")]
    partial class CreateSpeciesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PokeGame.Core.Abilities.Ability", b =>
                {
                    b.Property<int>("AbilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AbilityId"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("AbilityId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Key")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Abilities", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.Core.Moves.Move", b =>
                {
                    b.Property<int>("MoveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MoveId"));

                    b.Property<int?>("Accuracy")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("Power")
                        .HasColumnType("integer");

                    b.Property<int>("PowerPoints")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("MoveId");

                    b.HasIndex("WorldId", "Accuracy");

                    b.HasIndex("WorldId", "Category");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Key")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Power");

                    b.HasIndex("WorldId", "PowerPoints");

                    b.HasIndex("WorldId", "Type");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Moves", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.Core.Regions.Region", b =>
                {
                    b.Property<int>("RegionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RegionId"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("RegionId");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Key")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Regions", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.Core.Species.PokemonSpecies", b =>
                {
                    b.Property<int>("SpeciesId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SpeciesId"));

                    b.Property<int>("BaseFriendship")
                        .HasColumnType("integer");

                    b.Property<int>("CatchRate")
                        .HasColumnType("integer");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("EggCycles")
                        .HasColumnType("integer");

                    b.Property<string>("GrowthRate")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.Property<string>("PrimaryEggGroup")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("SecondaryEggGroup")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("SpeciesId");

                    b.HasIndex("WorldId", "BaseFriendship");

                    b.HasIndex("WorldId", "CatchRate");

                    b.HasIndex("WorldId", "Category");

                    b.HasIndex("WorldId", "CreatedBy");

                    b.HasIndex("WorldId", "CreatedOn");

                    b.HasIndex("WorldId", "EggCycles");

                    b.HasIndex("WorldId", "GrowthRate");

                    b.HasIndex("WorldId", "Id")
                        .IsUnique();

                    b.HasIndex("WorldId", "Key")
                        .IsUnique();

                    b.HasIndex("WorldId", "Name");

                    b.HasIndex("WorldId", "Number")
                        .IsUnique();

                    b.HasIndex("WorldId", "PrimaryEggGroup");

                    b.HasIndex("WorldId", "SecondaryEggGroup");

                    b.HasIndex("WorldId", "UpdatedBy");

                    b.HasIndex("WorldId", "UpdatedOn");

                    b.HasIndex("WorldId", "Version");

                    b.ToTable("Species", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.Core.Species.RegionalNumber", b =>
                {
                    b.Property<int>("SpeciesId")
                        .HasColumnType("integer");

                    b.Property<int>("RegionId")
                        .HasColumnType("integer");

                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("SpeciesId", "RegionId");

                    b.HasIndex("RegionId", "Number")
                        .IsUnique();

                    b.ToTable("RegionalNumbers", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.Core.Worlds.World", b =>
                {
                    b.Property<int>("WorldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorldId"));

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.HasKey("WorldId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedOn");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Name");

                    b.HasIndex("OwnerId");

                    b.HasIndex("UpdatedBy");

                    b.HasIndex("UpdatedOn");

                    b.HasIndex("Version");

                    b.ToTable("Worlds", "Pokemon");
                });

            modelBuilder.Entity("PokeGame.Infrastructure.HistoryRecord", b =>
                {
                    b.Property<int>("HistoryRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("HistoryRecordId"));

                    b.Property<string>("EventData")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime>("OccurredOn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceKind")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<long>("Version")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("HistoryRecordId");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("EventType");

                    b.HasIndex("OccurredOn");

                    b.HasIndex("UserId");

                    b.HasIndex("Version");

                    b.HasIndex("WorldId", "ResourceKind", "ResourceId");

                    b.ToTable("History", (string)null);
                });

            modelBuilder.Entity("PokeGame.Core.Abilities.Ability", b =>
                {
                    b.HasOne("PokeGame.Core.Worlds.World", "World")
                        .WithMany("Abilities")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("PokeGame.Core.Moves.Move", b =>
                {
                    b.HasOne("PokeGame.Core.Worlds.World", "World")
                        .WithMany("Moves")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("PokeGame.Core.Regions.Region", b =>
                {
                    b.HasOne("PokeGame.Core.Worlds.World", "World")
                        .WithMany("Regions")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("PokeGame.Core.Species.PokemonSpecies", b =>
                {
                    b.HasOne("PokeGame.Core.Worlds.World", "World")
                        .WithMany("Species")
                        .HasForeignKey("WorldId")
                        .HasPrincipalKey("Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("World");
                });

            modelBuilder.Entity("PokeGame.Core.Species.RegionalNumber", b =>
                {
                    b.HasOne("PokeGame.Core.Regions.Region", "Region")
                        .WithMany("RegionalNumbers")
                        .HasForeignKey("RegionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PokeGame.Core.Species.PokemonSpecies", "Species")
                        .WithMany("RegionalNumbers")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Region");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("PokeGame.Core.Regions.Region", b =>
                {
                    b.Navigation("RegionalNumbers");
                });

            modelBuilder.Entity("PokeGame.Core.Species.PokemonSpecies", b =>
                {
                    b.Navigation("RegionalNumbers");
                });

            modelBuilder.Entity("PokeGame.Core.Worlds.World", b =>
                {
                    b.Navigation("Abilities");

                    b.Navigation("Moves");

                    b.Navigation("Regions");

                    b.Navigation("Species");
                });
#pragma warning restore 612, 618
        }
    }
}
